stages: 
    - build
    - test
    - deploy

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - ~/.m2/repository
  key: "$CI_JOB_REF_NAME"
  untracked: true


# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
.validate: &validate
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'

mvn-package: 
  stage: build
  image: maven:3.3.9-jdk-8
  script: 
    - 'mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true'

# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
#.verify: &verify
#  stage: test
#  script:
#    - 'mvn $MAVEN_CLI_OPTS verify site site:stage'
#  only:
#    - master

mvn-test: 
  stage: test
  image: maven:3.3.9-jdk-8
  script: 
    - 'mvn $MAVEN_CLI_OPTS test'


# Validate merge requests using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.3.9-jdk-8


snapshotdeploy:
  stage: deploy
  image: maven:3.3.9-jdk-8
  only: 
    - develop
  script: 
    - 'mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true deploy:deploy'
