stages: 
    - build
    - test
    - deploy

image: maven:3.6.3-openjdk-11

cache:
  paths:
    - ~/.m2/repository
  untracked: true

mvn-package: 
  stage: build
  script:
    - mvn clean compile

mvn-test: 
  stage: test
  script:
    - mvn test

snapshotdeploy:
  stage: deploy
#  only:
#    - develop
  script: 
    - mvn package deploy:deploy
