/* Do not edit this file, because it is generated by maven plugin!!! */
package de.dailab.jiactng;
public final class Version
{	
	private final static String NAME  		= "agentCore";	
	private final static String NUMBER  	= "0.0.1-SNAPSHOT";
	private final static String TIMESTAMP	= "30.07.2007 18:53:10";
	
	/**
	 *	@return jiac revision name 
	 */
	public static final String getName() { 
		return NAME;
	}
	
	/**
	 *	@return jiac revision version 
	 */
	public static final String getNumber() { 
		return NUMBER;
	}
	
	/**
	 *	@return jiac revision date 
	 */
	public static final String getTimestamp() { 
		return TIMESTAMP;		
	}
}